# Local development profile - uses localhost Postgres
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bossbot}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Set true for local development only - disables security (no Google login needed) to simplify testing
app.security.permit-all=true

# JWT settings
# 5h
jwt.expiration.milliseconds=18000000

# Uncomment, if localhost Google login fails on local dev:
# app.cookie.secure=false
